
services:
  stock_market_database:
    image: postgres
    container_name: stock-market-database
    environment:
    - POSTGRES_DB=stock_market
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
    ports:
      - "8091:5432"

  stock_market:
    container_name: stock-market-backend-application
    depends_on:
      - stock_market_database
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stock_market_database:5432/stock_market
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"
