# импорт базового образа, имя образа: его версия
FROM postgres:latest
#устанавливаем переменные
ENV POSTGRES_DB stock_market
ENV POSTGRES_USER admin
ENV POSTGRES_PASSWORD admin
#копируем файл/папку в контейнер
COPY init.sql docker-entrypoint-initdb.d/init.sql